In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as mpl
import seaborn as sb
import plotly.express as px
import plotly.graph_objects as go
import plotly.io as pio
import plotly.colors as colors
from seaborn import color_palette

Data = pd.read_csv('Superstore.csv', encoding='Latin-1')

In [2]:
Data.head(5)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [3]:
Data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   object
 2   Order Date     9994 non-null   object
 3   Ship Date      9994 non-null   object
 4   Ship Mode      9994 non-null   object
 5   Customer ID    9994 non-null   object
 6   Customer Name  9994 non-null   object
 7   Segment        9994 non-null   object
 8   Country        9994 non-null   object
 9   City           9994 non-null   object
 10  State          9994 non-null   object
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   object
 13  Product ID     9994 non-null   object
 14  Category       9994 non-null   object
 15  Sub-Category   9994 non-null   object
 16  Product Name   9994 non-null   object
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), object(15)
memory usage: 1.6+ MB

In [4]:
Data['Order Date'] = pd.to_datetime(Data['Order Date'])
Data['Ship Date'] = pd.to_datetime(Data['Ship Date'])

In [5]:
Data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   object
 2   Order Date     9994 non-null   datetime64[ns]
 3   Ship Date      9994 non-null   datetime64[ns]
 4   Ship Mode      9994 non-null   object
 5   Customer ID    9994 non-null   object
 6   Customer Name  9994 non-null   object
 7   Segment        9994 non-null   object
 8   Country        9994 non-null   object
 9   City           9994 non-null   object
 10  State          9994 non-null   object
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   object
 13  Product ID     9994 non-null   object
 14  Category       9994 non-null   object
 15  Sub-Category   9994 non-null   object
 16  Product Name   9994 non-null   object
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: datetime64[ns](2), float64(3), int64(3), object(13)
memory usage: 1.6+ MB

In [6]:
Data['Order Month'] = Data['Order Date'].dt.month
Data['Order Year'] = Data['Order Date'].dt.year
Data['Order_Day_Of_Week'] = Data['Order Date'].dt.dayofweek
print(Data)

      Row ID        Order ID Order Date  Ship Date       Ship Mode  \
0          1  CA-2016-152156 2016-11-08 2016-11-11    Second Class
1          2  CA-2016-152156 2016-11-08 2016-11-11    Second Class
2          3  CA-2016-138688 2016-06-12 2016-06-16    Second Class
3          4  US-2015-108966 2015-10-11 2015-10-18  Standard Class
4          5  US-2015-108966 2015-10-11 2015-10-18  Standard Class
...      ...             ...        ...        ...             ...
9989    9990  CA-2014-110422 2014-01-21 2014-01-23    Second Class
9990    9991  CA-2017-121258 2017-02-26 2017-03-03  Standard Class
9991    9992  CA-2017-121258 2017-02-26 2017-03-03  Standard Class
9992    9993  CA-2017-121258 2017-02-26 2017-03-03  Standard Class
9993    9994  CA-2017-119914 2017-05-04 2017-05-09    Second Class

     Customer ID     Customer Name    Segment        Country             City  \
0       CG-12520       Claire Gute   Consumer  United States        Henderson
1       CG-12520       Claire Gute   Consumer  United States        Henderson
2       DV-13045   Darrin Van Huff  Corporate  United States      Los Angeles
3       SO-20335    Sean O'Donnell   Consumer  United States  Fort Lauderdale
4       SO-20335    Sean O'Donnell   Consumer  United States  Fort Lauderdale
...          ...               ...        ...            ...              ...
9989    TB-21400  Tom Boeckenhauer   Consumer  United States            Miami
9990    DB-13060       Dave Brooks   Consumer  United States       Costa Mesa
9991    DB-13060       Dave Brooks   Consumer  United States       Costa Mesa
9992    DB-13060       Dave Brooks   Consumer  United States       Costa Mesa
9993    CC-12220      Chris Cortes   Consumer  United States      Westminster

      ...         Category  Sub-Category  \
0     ...        Furniture     Bookcases
1     ...        Furniture        Chairs
2     ...  Office Supplies        Labels
3     ...        Furniture        Tables
4     ...  Office Supplies       Storage
...   ...              ...           ...
9989  ...        Furniture   Furnishings
9990  ...        Furniture   Furnishings
9991  ...       Technology        Phones
9992  ...  Office Supplies         Paper
9993  ...  Office Supplies    Appliances

                                           Product Name     Sales Quantity  \
0                     Bush Somerset Collection Bookcase  261.9600        2
1     Hon Deluxe Fabric Upholstered Stacking Chairs,...  731.9400        3
2     Self-Adhesive Address Labels for Typewriters b...   14.6200        2
3         Bretford CR4500 Series Slim Rectangular Table  957.5775        5
4                        Eldon Fold 'N Roll Cart System   22.3680        2
...                                                 ...       ...      ...
9989                             Ultra Door Pull Handle   25.2480        3
9990  Tenex B1-RE Series Chair Mats for Low Pile Car...   91.9600        2
9991                              Aastra 57i VoIP phone  258.5760        2
9992  It's Hot Message Books with Stickers, 2 3/4" x 5"   29.6000        4
9993  Acco 7-Outlet Masterpiece Power Center, Wihtou...  243.1600        2

     Discount    Profit  Order Month  Order Year  Order_Day_Of_Week
0        0.00   41.9136           11        2016                  1
1        0.00  219.5820           11        2016                  1
2        0.00    6.8714            6        2016                  6
3        0.45 -383.0310           10        2015                  6
4        0.20    2.5164           10        2015                  6
...       ...       ...          ...         ...                ...
9989     0.20    4.1028            1        2014                  1
9990     0.00   15.6332            2        2017                  6
9991     0.20   19.3932            2        2017                  6
9992     0.00   13.3200            2        2017                  6
9993     0.00   72.9480            5        2017                  3

[9994 rows x 24 columns]

In [7]:
Data.head(5)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Order Month,Order Year,Order_Day_Of_Week
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136,11,2016,1
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820,11,2016,1
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714,6,2016,6
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,10,2015,6
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164,10,2015,6

MONTHLY SALES

In [8]:
sales_by_month= Data.groupby('Order Month')['Sales'].sum().reset_index()
# Customizing labels (maps column names to display names)
labels_dict = {'Order Month': 'Month', 'Sales': 'Revenue ($)'}
fig = px.line(sales_by_month, x='Order Month', y='Sales', title='Sales by Month',
labels=labels_dict)
# Optional: Further layout customization (e.g., center the title)
fig.update_layout(title_x=0.5)
# If you need to show markers on the line as well:
fig.update_traces(mode='lines+markers')
fig.show()

In [9]:
# 1. Group the data
sales_by_month = Data.groupby('Order Month')['Sales'].sum().reset_index()
# 2. (Optional) Create a formatted label column if you want currency formatting
# This makes the labels look cleaner (e.g., "$1,200.00")
sales_by_month['Sales_Label'] = sales_by_month['Sales'].apply(lambda x: f"${x:,.2f}")
# 3. Create the plot using the 'text' parameter
fig = px.line(
    sales_by_month,
    x='Order Month',
    y='Sales',
    title='Sales by Month',
    text='Sales_Label'  # This adds the labels
)
# 4. Update the trace to position the labels
fig.update_traces(textposition='top center')
fig.show()

SALES BY CATEGORY

In [10]:
sales_by_category= Data.groupby('Category')['Sales'].sum().reset_index()
fig = px.pie(sales_by_category,names='Category',values='Sales',title='Sales by Category')
# 3. Increase height and width
fig.update_layout(
    width=700,   # Set your desired width in pixels
    height=600   # Set your desired height in pixels
)
# 4. Show both Labels and Values together
fig.update_traces(
    textinfo='label+value', # Combines label and value
    textposition='outside'  # Optional: places the text outside the slices for better readability
)
fig.show()

SALES BY SUB-CATEGORY

In [11]:
sales_by_subcategory= Data.groupby('Sub-Category')['Sales'].sum().reset_index()
fig = px.pie(sales_by_subcategory,names='Sub-Category',values='Sales',hole=0.4,title='Sales by Sub-Category')
# 3. Increase height and width
fig.update_layout(
    width=700,   # Set your desired width in pixels
    height=600   # Set your desired height in pixels
)
# 4. Show both Labels and Values together
fig.update_traces(
    textinfo='label+value', # Combines label and value
    textposition='outside'  # Optional: places the text outside the slices for better readability
)
fig.show()

SALES BY MONTHLY PROFIT

In [12]:
sales_by_monthly_profit= Data.groupby('Order Month')['Profit'].sum().reset_index()
# 2. Create a formatted label column for the values (e.g., "$1,234.56")
sales_by_monthly_profit['Profit_Label'] = sales_by_monthly_profit['Profit'].apply(lambda x: f"${x:,.2f}")
fig = px.bar(sales_by_monthly_profit, x='Order Month', y='Profit', title='Sales by Monthly Profit',text='Profit_Label')
# 4. Increase height & width and update text position
fig.update_layout(
    height=600,  # Adjust height (in pixels)
    width=750   # Adjust width (in pixels)
)
# Position the text on top of the bars
fig.update_traces(textposition='outside')
fig.show()

PROFIT BY CATEGORY

In [13]:
sales_by_category_profit= Data.groupby('Category')['Profit'].sum().reset_index()
# 2. Create a formatted label column for the values (e.g., "$1,234.56")
sales_by_category_profit['Profit_Label'] = sales_by_category_profit['Profit'].apply(lambda x: f"${x:,.2f}")
fig = px.bar(sales_by_category_profit, x='Category', y='Profit', title='Sales by Category Profit',text='Profit_Label')
# 4. Increase height & width and update text position
fig.update_layout(
    height=600,  # Adjust height (in pixels)
    width=750   # Adjust width (in pixels)
)
# Position the text on top of the bars
fig.update_traces(textposition='outside')
fig.show()

SALES VS PROFIT BY CUSTOMER SEGMENT

In [14]:
# 1. Group the data
sales_vs_profit_by_customer_segment = Data.groupby('Segment').agg({'Sales':'sum', 'Profit':'sum'}).reset_index()
# 2. Define the color palette
color_palette = colors.qualitative.Pastel
# 3. Initialize the figure
fig = go.Figure()
# 4. Add the 'Sales' bar
fig.add_trace(go.Bar(
    x=sales_vs_profit_by_customer_segment['Segment'],
    y=sales_vs_profit_by_customer_segment['Sales'],
    name='Sales',
    marker_color=color_palette[0],
    text=sales_vs_profit_by_customer_segment['Sales'].apply(lambda x: f'${x:,.0f}'), # Add text labels
    textposition='auto' # Automatically place labels
))
# 5. Add the 'Profit' bar
fig.add_trace(go.Bar(
    x=sales_vs_profit_by_customer_segment['Segment'],
    y=sales_vs_profit_by_customer_segment['Profit'],
    name='Profit',
    marker_color=color_palette[1],
    text=sales_vs_profit_by_customer_segment['Profit'].apply(lambda x: f'${x:,.0f}'), # Add text labels
    textposition='auto' # Automatically place labels
))
# 6. Update layout for size, grouping, and labels
fig.update_layout(
    title='Sales vs Profit by Customer Segment',
    xaxis_title='Segment',
    yaxis_title='Amount',
    barmode='group', # Puts bars side-by-side
    height=600,      # Increase height
    width=750       # Increase width
)
fig.show()

SALES VS PROFIT RATIO

In [15]:
svpbcs = Data.groupby('Segment').agg({'Sales':'sum', 'Profit':'sum'}).reset_index()
svpbcs['SALES TO PROFIT RATIO']=svpbcs['Sales']/svpbcs['Profit']
print(svpbcs)

       Segment         Sales       Profit  SALES TO PROFIT RATIO
0     Consumer  1.161401e+06  134119.2092               8.659471
1    Corporate  7.061464e+05   91979.1340               7.677245
2  Home Office  4.296531e+05   60298.6785               7.125416